synonym_dict = {
    "Store ID": ["Store_ID", "Store Identifier", "Outlet_ID", "Shop ID", "Retail ID", "Branch ID", "restaurant_id"],
    "Store Name": ["Shop Name", "Outlet Name", "Store Name", "Retail Name", "Branch Name","restaurant"],
    "Store Size": ["Shop Size", "Outlet Size", "Store Size", "Retail Size", "Branch Size"],
    "Region/Zone": ["Region", "Zone", "Area", "Region/Zone", "Territory", "District"],
    "Product_id": ["Product ID", "Item ID", "Prod_ID", "Product_id", "SKU", "Product Code"],
    "Category": ["Product Category", "Type", "Category", "Class", "Group"],
    "Location": ["Address","address", "Store Location", "Location", "Site", "Venue", "user_data_country_id","location"],
    "Latitude": ["latitude", "Lat", "Latitude", "Lat", "Latitude", "Lat"],
    "Longitude": ["longitude", "Long", "longitude", "Long", "Long"],
    "Purchase Amount (USD)": ["Transaction_ID","Amount", "Transaction Value", "Total Spend", "Purchase Amount (USD)", "Expenditure", "Cost","total_order","Price_Per_Item"],
    "Promo_code": ["Discount Code", "Promotion Code", "Promo_code", "Voucher Code", "Coupon Code"],
    "Discount": ["discount","Discount", "Discount Amount", "Discount Value", "Discount Percentage", "Discount Rate"],
    "Date": ["Transaction Date", "Purchase Date", "Order Date", "date", "Date", "Day", "Time"],
    "Previous Purchases": ["Past Purchases", "Historical Purchases", "Previous Purchases", "Earlier Purchases", "Prior Purchases"],
    "Age": ["Customer Age", "Years", "Age", "Customer Years", "Client Age"],
    "Gender": ["Sex", "Customer Gender", "Gender", "Client Gender", "User Gender", "gender"],
    "Review Rating": ["Rating", "Customer Feedback", "Stars", "Review Rating", "Score", "Evaluation","rating"],
    "Customer_ID": ["Customer ID", "Client_ID", "User_ID", "Customer_ID", "Client Number", "User Number","user_data_id"],
    "Churned": ["Churned", "Left", "Churned", "Exited", "Churned", "Departed"],
    # "user_data_name": ["user_data_name"],
    # "user_data_email": ["user_data_email"],
    # "user_data_phone_no": ["user_data_phone_no"],
    # "user_data_status": ["user_data_status"],
    # "user_data_created_at": ["user_data_created_at"],
    # "user_data_updated_at": ["user_data_updated_at"],
    # "user_data_service_id": ["user_data_service_id"],
    # "user_data_whatsapp_verification_code": ["user_data_whatsapp_verification_cgstode"],
    # "user_data_phone_verified_at": ["user_data_phone_verified_at"],
    # "user_data_active_status": ["user_data_active_status"],
    # "Priority_delivery_time": ["Priority_delivery_time"],
    # "this_week_order_count": ["this_week_order_count"],
    # "active": ["active"],
    # "group_id": ["group_id"],
    # "pos_system": ["pos_system"],
    # "food_section": ["food_section"],
    # "day": ["day"],
    # # "total_order": ["total_order"],
    # "delivery": ["delivery"],
    # "phone": ["phone"],
    "code": ["code"],
    # "delivery_time": ["delivery_time"],
    # "cover_photo": ["cover_photo"],
    # "latitude": ["latitude"],
    # "country_id": ["country_id"],
    # # "rating": ["rating"],
    # "self_delivery_system": ["self_delivery_system"],
    # "balance": ["balance"],
    # "updated_at": ["updated_at"],
    # "quicky_delivery": ["quicky_delivery"],
    "gst_code": ["gst_code"],
    # "currency": ["currency"],
    # "zone_id": ["zone_id"],
    # "todays_earning": ["todays_earning"],
    # "schedule_order": ["schedule_order"],
    # "off_day": ["off_day"],
    # "gst_status": ["gst_status"],
    # "this_week_earning": ["this_week_earning"],
    # "this_month_order_count": ["this_month_order_count"],
    # "veg": ["veg"],
    # "available_time_starts": ["available_time_starts"],
    # "closing_time": ["closing_time"],
    # "available_time_ends": ["available_time_ends"],
    # "todays_order_count": ["todays_order_count"],
    # "is_quick": ["is_quick"],
    # "email": ["email"],
    # "free_delivery": ["free_delivery"],
    # "status": ["status"],
    # "f_name": ["f_name"],
    # "total_earning": ["total_earning"],
    # "alpha_3": ["alpha_3"],
    # "minimum_order": ["minimum_order"],
    # "comission": ["comission"],
    # "closeing_time": ["closeing_time"],
    # "logo": ["logo"],
    # "restaurant_category": ["restaurant_category"],
    # "created_at": ["created_at"],
    # "this_month_earning": ["this_month_earning"],
    # "order_count": ["order_count"],
    # "take_away": ["take_away"],
    # "opening_time": ["opening_time"],
    # "non_veg": ["non_veg"],
    # "symbol": ["symbol"],
    # "rating_count": ["rating_count"],
    # "tax": ["tax"],
    # "taxpayer_number": ["taxpayer_number"],
    # "id": ["id"],
    # "name": ["name"],
    # "restaurant": ["restaurant"],
    # "member_since_days": ["member_since_days"],
    # "l_name": ["l_name"],
    # "is_group": ["is_group"],
    # "admin_id": ["admin_id"],
    # "reviews_section": ["reviews_section"],
    # "vendor_id": ["vendor_id"],
    # "delivery_charge": ["delivery_charge"],
    # "longitude": ["longitude"],
    # "Express_delivery_time": ["Express_delivery_time"],
    # # "avg_rating": ["avg_rating"],
    # "cash_in_hands": ["cash_in_hands"],
    # "timezone": ["timezone"]
}
